services:
  backend:
    build: .
    ports:
      - "4000:4000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/sondages
    depends_on:
      - mongo
    networks:
      - sondacs-network

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - sondacs-network

  frontend:
    image: nginx:alpine
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports:
      - "8088:80"
    networks:
      - sondacs-network

networks:
  sondacs-network:
    driver: bridge
