services:
  backend:
    build: .
    restart: unless-stopped
    ports:
      - "${BACKEND_PORT}:4000"
    environment:
      - MONGO_URI=${MONGO_URI}
    depends_on:
      - mongo
    networks:
      - sondacs-network

  mongo:
    image: mongo
    restart: unless-stopped
    ports:
      - "${MONGO_PORT}:27017"
    networks:
      - sondacs-network

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - "${MONGO_EXPRESS_PORT}:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGO_EXPRESS_USERNAME}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_EXPRESS_PASSWORD}
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
    depends_on:
      - mongo
    networks:
      - sondacs-network

  frontend:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports:
      - "${FRONTEND_PORT}:80"
    networks:
      - sondacs-network

networks:
  sondacs-network:
    driver: bridge
