services:
  backend:
    build: .
    ports:
      - "4000:4000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/sondages
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"

  frontend:
    image: nginx:alpine
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports:
      - "8080:80"

secrets:
  mongo_root_user:
    file: ./secrets/mongo_root_user.txt
  mongo_root_password:
    file: ./secrets/mongo_root_password.txt
  mongo_user_password:
    file: ./secrets/mongo_user_password.txt
  mongo_user:
    file: ./secrets/mongo_user.txt


networks:
  sondacs-network:
    driver: bridge